### ISSUE TITLE
[Functionality] Fetch mocks from recognized URLs

### ISSUE THREAD

**Issue by idantene** [unmock/unmock-vscode-plugin#3]
If the document contains direct calls to a URL, offer a "get mock now" link over URL.

Requirements and implementation:
- Statically find URLs via common libraries (i.e. `axios`, what else?)
- Statically recognize what parameters for the call are static/hard typed, and which are variables.
- Ask user to fill in information for variables.

**Comment by mikesol** [comment]
Not valid anymore in new-ish version of unmock
